enum WordList {
    static let words: [String] = [
        // 3–4 bokstäver
        "alm", "and", "apa", "arm", "ask", "bad", "bal", "barn",
        "berg", "bil", "blad", "blek", "blod", "blom", "bord", "borg", "brev",
        "bro", "brun", "brus", "bur", "bylta", "dal", "dam", "dikt",
        "dim", "djup", "doft", "dolk", "drom", "dryck", "duva", "eld",
        "ek", "falk", "fara", "fart", "fest", "filt", "fisk", "flag",
        "flog", "fors", "fred", "frid", "fris", "frog", "frukt", "full",
        "gata", "gest", "gift", "glad", "glas", "gles", "glod", "gnista",
        "gott", "gran", "grav", "grep", "gris", "grop", "grov", "grus",
        "gult", "gung", "gyllen",
        "hamn", "hand", "hare", "harv", "hast", "hatt", "havs", "hel",
        "helm", "het", "hink", "hjul", "holk", "hon", "hopp", "horn",
        "hund", "hus", "hylla", "hyra",
        "igelkott", "is", "jakt", "jord", "jul", "jungfru",
        "kall", "kalv", "kam", "kamp", "kan", "kant", "karl", "karta",
        "katt", "kedja", "kirk", "klam", "klang", "klart", "klippa", "klok",
        "kniv", "knut", "kopp", "kork", "korn", "kort", "kraft", "kran",
        "krig", "krok", "krona", "krus", "kung", "kust", "kvarn", "kvist",
        "lake", "lamm", "land", "larm", "last", "led", "lek", "lejon",
        "lid", "lila", "lilja", "lind", "ljud", "ljung", "ljus", "lock",
        "loft", "lopp", "lugn", "lund", "luft", "lust", "lyft", "lykta",
        "mal", "malm", "mark", "mars", "mask", "mast", "matt", "med",
        "mild", "mjuk", "moln", "mord", "moss", "mull", "munk", "mur",
        "mynt", "myr",
        "natt", "nav", "nit", "nord", "norr", "nos", "nyckel",
        "orm", "ost", "ovan", "oxe",
        "palm", "pank", "pil", "plats", "plog", "pris", "prakt", "puls",
        "rand", "ren", "rik", "ring", "ris", "rit", "rock", "ron",
        "rop", "ros", "rost", "rund", "rygg", "rymd",
        "salt", "sand", "sak", "sed", "segel", "sida", "sjal", "skog",
        "skola", "skor", "skott", "slang", "slott", "slug", "slut", "smak",
        "smed", "smog", "snabb", "snar", "sno", "snok", "sol", "sommar",
        "sort", "spark", "spel", "spets", "stad", "stall", "stam", "stark",
        "sten", "stil", "stol", "stor", "stork", "strand", "stuga",
        "sund", "svan", "svamp", "svans", "svart", "svin",
        "tall", "tand", "tarm", "tavla", "tegel", "tid", "tolk", "topp",
        "torg", "torn", "torr", "trad", "tram", "tro", "troll", "trumma",
        "trygg", "tung", "tupp", "tur",
        "ugn", "uggla", "ulv", "ung", "uppror",
        "vacker", "vagn", "vakt", "vals", "varm", "vass", "veck", "vig",
        "vild", "vilja", "vind", "vinge", "vit", "vrak", "vrede",
        "yxa",

        // 5–6 bokstäver
        "adel", "afton", "alder", "alska", "aning", "ankar", "antal",
        "atlas", "aveny",
        "bagge", "bakom", "balans", "banan", "banks", "befria", "begrav",
        "bjork", "blankt", "blixt", "blomma", "bocken", "brasa", "bredd",
        "broder", "brunn", "brygga", "bubbla", "bukett", "bytta",
        "cykel", "damm", "dans", "dimma", "djungel", "drake", "driva",
        "dubbel", "dunkel",
        "ekorre", "eldig", "energi", "enkel", "erbjud",
        "fabel", "fagel", "falla", "familj", "fason", "fiber", "figur",
        "fiende", "finger", "fjord", "flagga", "flicka", "flygel",
        "fogde", "foster", "frakt", "fresta", "frost", "frysa", "fukte",
        "gammal", "gardin", "gavel", "gevir", "gnistra", "granne", "grotta",
        "gruva", "gryning", "gunga", "gyllene",
        "hammar", "handel", "havre", "hemlighet", "hjort", "holme",
        "humle", "hyacint", "hymn",
        "isberg", "isande",
        "jungfrun", "juvelen",
        "kabel", "kajak", "kalas", "kamera", "kanin", "kapell",
        "karta", "klocka", "kloster", "koloni", "komma", "konung",
        "koppar", "kristall", "krydda", "kullen", "kvinna",
        "lager", "lansar", "lava", "ledare", "lever", "liknelse",
        "lindra", "ljuva", "lockelse", "lucka", "lycklig",
        "magi", "mangel", "melon", "minne", "mjolke", "modig",
        "molnet", "morgon", "mossa", "muren", "mylla",
        "nacke", "nagel", "naken", "natur", "nektar", "norden",
        "nunna", "nypon",
        "offer", "ombord", "ordning", "orkan",
        "panna", "panter", "parasoll", "pelare", "pilgrim",
        "pojke", "portal", "pulver", "punkt",
        "raket", "ranka", "rapport", "regnskog", "riddar",
        "rimfrost", "rolig", "rubrik", "runsten", "rustik",
        "saftig", "salvia", "sammet", "silver", "skapare",
        "skimmer", "skogen", "skuld", "slinga", "smaragd",
        "snille", "somrig", "spegel", "spjut", "springa",
        "stabil", "stavelse", "stigen", "stjarna", "stolpe",
        "stormen", "strimma", "stugan", "styrka", "svala",
        "syrlig",
        "talang", "tanke", "tecken", "tigare", "timjan",
        "tjader", "tornet", "trappa", "tropik", "trumslagare",
        "tunika", "turbin",
        "ungdom", "uppfinn",
        "vakna", "vandel", "vanlig", "vardag", "vatten",
        "vildmark", "viljan", "vinter", "visdom", "vuxen",
    ]
}
