enum WordList {
    static let words: [String] = [
        // Natur och växter
        "alm", "alv", "aster", "bark", "berg", "bild", "bio", "bjork",
        "blad", "blomma", "bok", "buske", "dal", "damm", "dimma", "dunge",
        "duva", "ek", "eld", "elm", "falk", "fauna", "filt", "fjord",
        "flora", "flod", "fors", "frost", "frukt", "fyr", "gran", "grav",
        "grind", "grop", "grus", "gryning", "gras", "gul", "hagg", "halm",
        "hampa", "hassel", "havre", "hed", "honung", "humle", "hyacint",
        "is", "jord", "karg", "korn", "kust", "kvarn", "kvist", "lag",
        "lagun", "land", "lava", "lilja", "lind", "ljung", "ljus", "luft",
        "lund", "malm", "mark", "moln", "mossa", "mull", "myr", "natur",
        "nypon", "oas", "oliv", "orre", "palm", "pil", "plommon", "poppel",
        "ravin", "ren", "ros", "ronn", "salvia", "sand", "sjal", "skog",
        "sky", "slant", "snok", "sol", "sommar", "strand", "sund", "svan",
        "svamp", "tall", "terra", "timjan", "topp", "torn", "torr", "trad",
        "tundra", "tuva", "vatten", "vide", "vind", "vinter", "viol",
        "alg", "ang",

        // Djur
        "and", "anka", "apa", "orre", "bagge", "bisamdjur", "bjorn",
        "bock", "buffel", "duva", "ekorre", "elefant", "fasan", "fisk",
        "flamingo", "fluga", "fogel", "galt", "geting", "giraff",
        "groda", "gris", "grodor", "hamster", "hare", "hast", "hind",
        "hjort", "hok", "hummer", "hund", "hyena", "igel", "jaguar",
        "kalkon", "kalv", "kamel", "kanin", "katt", "kobra", "kolibri",
        "ko", "korp", "krabba", "krokodil", "kraka", "lam", "lejon",
        "leopard", "lind", "lodjur", "lom", "lummer", "mal", "mink",
        "mops", "mus", "myra", "mard", "orm", "otter", "oxe", "panter",
        "papegoja", "puma", "ripa", "sik", "skata", "sork", "sparv",
        "stork", "svan", "tiger", "trana", "trast", "tupp", "uggla",
        "ulv", "varg", "val", "vipa", "vrak",

        // Kropp
        "arm", "axel", "ben", "blod", "brost", "fot", "hand", "hjarta",
        "hud", "huvud", "hals", "har", "kind", "kna", "kropp", "lang",
        "lever", "lunga", "mage", "mun", "muskel", "nacke", "nagel",
        "nasa", "nava", "ora", "panna", "rygg", "tand", "tunga",

        // Hem och hus
        "bad", "balkong", "bank", "bord", "borg", "brev", "bro", "duk",
        "dyna", "dorr", "fack", "fonster", "gaffel", "galler", "gardin",
        "golv", "gryta", "gard", "hall", "hamn", "hatt", "hem", "hink",
        "hjul", "hylla", "hus", "kam", "kamin", "kanna", "kedja", "kista",
        "klocka", "knapp", "kniv", "kopp", "kork", "kudde", "lampa",
        "lakan", "larm", "las", "lock", "lucka", "lykta", "matta",
        "mutter", "nyckel", "pall", "panna", "port", "pumpa", "puts",
        "ram", "ring", "rost", "ruta", "sax", "sked", "skor", "slang",
        "spegel", "spis", "stege", "stol", "stuga", "syll", "tak",
        "tavla", "tegel", "trappa", "tross", "trad", "ugn", "vagn",
        "vant", "vas",

        // Mat och dryck
        "bacon", "banan", "bulle", "brod", "citron", "dill", "deg",
        "druva", "fikon", "flask", "glass", "graddde", "gurka", "honung",
        "juice", "kaffe", "kaka", "krydda", "kummin", "lime", "lingon",
        "loka", "mandel", "melon", "mjolk", "morot", "mos", "nudel",
        "noga", "ost", "pasta", "peppar", "paron", "rakor", "russin",
        "sallad", "salt", "senap", "sirap", "smor", "socker", "soppa",
        "sylt", "te", "vanilj", "vatten", "vinbar",

        // Arbete och yrken
        "advokat", "baker", "bonde", "chef", "doktor", "domare", "fogde",
        "greve", "grov", "guide", "hertig", "ingenjor", "jakt", "kapten",
        "karl", "kirurg", "klerk", "kock", "kung", "kvinna", "lakare",
        "ledare", "lots", "malare", "man", "munk", "nunna", "officer",
        "pilot", "pojke", "polis", "prost", "raknare", "riddare", "smed",
        "snickare", "soldat", "tolk", "vakt", "vard",

        // Vapen och verktyg
        "ambolt", "bila", "borr", "dolk", "fil", "gaffel", "grep",
        "hammare", "harv", "mejsel", "motor", "nit", "plog", "rasp",
        "sag", "skiftnyckel", "slag", "slaga", "spade", "spett", "spik",
        "stake", "stans", "svarv", "tang", "vals", "yxa",

        // Samhälle och byggnad
        "arkiv", "arv", "asyl", "atlas", "aveny", "bio", "bro", "bruk",
        "byra", "dans", "dikt", "dom", "drott", "elit", "epos", "etos",
        "fakta", "familj", "fest", "flagga", "flykt", "folk", "fred",
        "frid", "front", "gata", "gest", "grupp", "grans", "hamn",
        "handel", "ideal", "kapell", "klubb", "koloni", "krig", "kultur",
        "kyrka", "lag", "lagen", "moral", "nation", "norm", "nyheter",
        "offer", "orden", "parti", "plats", "polis", "post", "press",
        "pris", "punkt", "rad", "rapport", "rest", "rike", "rit",
        "rummet", "saga", "skatt", "skick", "skola", "slott", "spar",
        "stad", "stat", "strid", "styre", "stall", "system", "tempel",
        "titel", "torg", "tornet", "tribunal", "triumf", "tull",
        "tunna", "uppror", "val", "vapen", "varda",

        // Känslor och egenskaper
        "arg", "blek", "blyg", "bred", "brun", "djup", "dum", "dyster",
        "enkel", "falsk", "fin", "flat", "fri", "frisk", "full", "glad",
        "gles", "god", "gott", "grov", "grym", "gyllen", "halvt",
        "hard", "het", "hel", "helig", "hopplost", "hov", "hungrig",
        "ivrig", "kall", "klar", "klok", "kort", "kvick", "lat",
        "ledig", "listig", "ljuv", "lugn", "lustig", "lydig", "lang",
        "matt", "mild", "mjuk", "modig", "mork", "naken", "noggrann",
        "nojd", "nyfiken", "olik", "ond", "rak", "rar", "ren", "rik",
        "rolig", "rund", "ratt", "saktmodig", "salt", "seg", "skarp",
        "slug", "slut", "smal", "smart", "snabb", "snar", "sotig",
        "spak", "stark", "stilla", "stor", "stolt", "strikt", "stum",
        "stygg", "sval", "svart", "saker", "sot", "tjock", "tom",
        "torr", "trang", "trygg", "tung", "tunn", "vacker", "vaken",
        "vanlig", "varm", "vass", "vid", "vild", "vis", "vit", "vig",
        "vred", "yster", "atal", "odla", "oppen",

        // Verb (grundform)
        "aga", "aka", "alskar", "anda", "ater", "bada", "baka", "banna",
        "basa", "basta", "bedja", "betala", "binda", "bita", "blasa",
        "bloda", "boja", "borja", "brinna", "bryta", "bygga", "bara",
        "dansa", "dela", "dofta", "doljer", "drar", "dricker", "driva",
        "dromma", "dyka", "doda", "falla", "fanga", "fara", "fasta",
        "festa", "finna", "fiska", "flyga", "flytta", "forma", "fraga",
        "frysa", "fylla", "folja", "ge", "glida", "gnistra", "grava",
        "gripa", "grata", "gunga", "ga", "gora", "gomma", "halla",
        "hamta", "handla", "hata", "helga", "hjalpa", "hoppa", "hugga",
        "halla", "hanga", "hora", "jaga", "jubla", "kalla", "kamma",
        "kanna", "kasta", "klaga", "klappa", "klara", "kliva", "klyva",
        "knyta", "koka", "komma", "korsa", "krama", "krava", "kunna",
        "kopa", "kora", "landa", "langa", "lasa", "leda", "leka",
        "leta", "leva", "lida", "ligga", "likna", "lista", "ljuga",
        "lossa", "lova", "lyda", "lysa", "lysta", "lagga", "lamna",
        "lara", "lasa", "losa", "mala", "mata", "mena", "minska",
        "mista", "mota", "nalkas", "nappa", "nika", "njuta", "nosa",
        "odla", "ordna", "orka", "packa", "passa", "peka", "plana",
        "plocka", "ploga", "prova", "prygla", "raka", "rana", "rasa",
        "regna", "resa", "rida", "ringa", "rita", "riva", "ropa",
        "rubba", "rulla", "ruska", "rysa", "racka", "radda", "rakna",
        "rora", "salta", "samla", "segla", "simma", "sitta", "sjuda",
        "sjunga", "skada", "skaka", "skapa", "skina", "skjuta", "skola",
        "skota", "skriva", "skryta", "skura", "skynda", "slipa", "slita",
        "sluta", "smaka", "smida", "smyga", "snurra", "sola", "sopa",
        "sova", "spara", "spela", "spilla", "sprida", "sparka", "stanna",
        "stava", "steka", "stiga", "stjala", "stoppa", "stryka", "strova",
        "studa", "stanga", "stoda", "suga", "susa", "svara", "svika",
        "svalka", "svanga", "synas", "sanda", "soka", "tala", "tanka",
        "tappa", "tiga", "titta", "torka", "trava", "trivas", "trycka",
        "trana", "trosta", "tumla", "tvatta", "vakna", "vandra", "vanka",
        "vaxa", "veta", "vika", "vila", "vinna", "visa", "viska",
        "vilja", "vaga", "vanda", "vanta", "varma", "alder",

        // Tid och rum
        "afton", "dag", "fas", "gang", "helg", "hora", "host",
        "igar", "juli", "juni", "karta", "klocka", "kvall", "mars",
        "minut", "moment", "morgon", "natt", "nord", "norr", "nyvaken",
        "oster", "period", "plats", "rymd", "sekund", "sommar",
        "soder", "tempo", "tid", "timma", "vaster", "vinter", "var",
        "vecka", "zon",

        // Abstrakta begrepp
        "anda", "aning", "art", "balans", "band", "behov", "bevis",
        "bot", "bredd", "brist", "bruk", "charm", "daning", "drom",
        "dygd", "dust", "djarvhet", "energi", "fara", "fason", "feber",
        "figur", "flykt", "form", "fort", "fras", "gagn", "gald",
        "gift", "gissning", "glans", "glimt", "gnistra", "grad", "hamnd",
        "heder", "hopp", "hunger", "hast", "hymn", "ide", "insikt",
        "kapital", "karma", "kaos", "klang", "kraft", "kris", "kropp",
        "kvot", "list", "logi", "logik", "lust", "lust", "lycka",
        "makt", "mandat", "metod", "minus", "minskning", "mod", "modus",
        "mynt", "matt", "nod", "odds", "ordning", "orsak", "pakt",
        "pant", "parti", "plan", "plikt", "princip", "profil", "prakt",
        "puls", "rand", "ras", "recept", "regel", "rekord", "resultat",
        "risk", "roll", "rubrik", "rum", "runda", "rutin", "saga",
        "sinne", "skam", "skuld", "skald", "slump", "smart", "smarta",
        "sorg", "spar", "spets", "spjut", "sprak", "stank", "stank",
        "stil", "styrka", "sunda", "svek", "svar", "symbol", "synd",
        "satt", "tanke", "teknik", "teori", "term", "tema", "test",
        "ton", "topp", "trend", "tro", "trohet", "trupp", "typ", "tur",
        "tvivel", "umgang", "uppgift", "urval", "vana", "vara", "vardag",
        "varde", "vag", "visdom", "vilja", "vinst", "vuxen", "yta",
        "ode", "onskan",

        // Färger och material
        "blond", "brons", "cement", "glas", "gra", "guld", "gyllen",
        "gron", "jade", "koppar", "krita", "lack", "lader", "linne",
        "marmor", "metall", "rosa", "rost", "siden", "silver", "skiffer",
        "stahl", "sten", "svart", "tenn", "ull", "vit",

        // Musik och konst
        "ackord", "aria", "balad", "bas", "dans", "drill", "dur",
        "fagott", "flojt", "fuga", "harpa", "horn", "hymn", "klocka",
        "koral", "lyra", "mars", "melodi", "moll", "musik", "not",
        "oboe", "opera", "orgel", "piano", "psalm", "puka", "riff",
        "saga", "sats", "solo", "sonat", "strok", "takt", "tema",
        "tenor", "ton", "trombon", "trumpet", "trumma", "tuba", "vals",
        "vers", "visa", "viol",

        // Fler substantiv
        "aktie", "ankel", "ankare", "areal", "askan", "backe", "bagare",
        "balsam", "barbar", "basker", "basun", "batong", "beratt",
        "besked", "betong", "blick", "blindt", "blossa", "bohem",
        "bojelse", "bokmal", "bonad", "borgen", "brand", "brasa",
        "brygga", "bubbla", "bukett", "bunke", "buskage", "byra",
        "cirkel", "cykel", "dager", "datum", "dekret", "deponi",
        "detalj", "dialog", "docka", "dolk", "drake", "dunkel",
        "dusch", "dvala", "epok", "essens", "etikett", "export",
        "fabel", "fackel", "falang", "falska", "faner", "farkost",
        "fasad", "fiber", "finger", "flagga", "flaske", "flicka",
        "flinga", "flocken", "florett", "flyg", "fogel", "folkslag",
        "format", "fossil", "fragor", "frakt", "frosten", "frusen",
        "fullmakt", "fura", "foting",
        "galax", "galler", "garanti", "gavel", "gevir", "glaciar",
        "gloria", "gnista", "gossen", "granne", "gravyr", "grotta",
        "gruva", "gudinna", "gummi",
        "hallon", "hammare", "handbok", "harv", "hemlighet", "herold",
        "hjord", "holme", "humla", "husdjur", "hydra",
        "ibland", "ideal", "imma", "import", "index", "insats",
        "isberg", "island",
        "jaspis", "jogga", "jordbro", "jubel", "juvel",
        "kabel", "kadett", "kajak", "kakao", "kalas", "kamera",
        "kamrat", "kandis", "kapell", "karavan", "kasett", "kavaljer",
        "kemist", "kiosk", "kista", "klammer", "klient", "klister",
        "kloster", "knopp", "koffert", "kolumn", "kompass", "konsert",
        "konst", "kontor", "korall", "korgen", "kosmos", "kredit",
        "kristall", "krukor", "kummel", "kupol", "kursor", "kurva",
        "kutter",
        "lager", "lansar", "lavin", "legend", "lera", "letar",
        "limpa", "linbana", "linje", "lokal", "lottas", "lucka",
        "lyrik",
        "magasin", "mandel", "mantel", "maskin", "matsal", "medel",
        "minut", "modul", "molnfri", "moped", "mosaik", "mullvad",
        "murbruk", "myndig",
        "nation", "nektar", "notering", "novell", "nutid",
        "obelisk", "ocean", "offert", "omfamna", "optik", "orkan",
        "oval",
        "paddel", "pagod", "palett", "panel", "parad", "patron",
        "pedal", "pelare", "pendel", "pergola", "person", "pilgrim",
        "pinne", "pistol", "planka", "ploga", "plommon", "portal",
        "profet", "propell", "provins", "pulver",
        "radar", "raket", "ranka", "rapport", "redskap", "reflex",
        "reform", "regent", "rektor", "relief", "remmar", "resort",
        "resurs", "revolt", "rikedom", "robot", "roman", "ronell",
        "runsten", "rustik", "rytm",
        "safran", "salong", "sammet", "satellit", "satin", "scen",
        "sedel", "sektor", "signal", "sirkel", "siren", "skafferi",
        "skapare", "skelett", "skimmer", "skinka", "skjorta", "skogen",
        "skorsten", "slagfalt", "slinga", "smaragd", "snille", "sockel",
        "soldat", "sparv", "spiral", "springa", "stabil", "stativ",
        "stempel", "stigen", "stjarna", "stolpe", "stormen", "strimma",
        "strumpa", "stubbe", "stupror", "stavar", "syrlig",
        "tablett", "talang", "tandem", "tecken", "termos", "textil",
        "tiger", "tjader", "tonika", "topas", "torped", "traktor",
        "tredje", "tribun", "troffel", "tropisk", "trumslagare", "turbin",
        "turism", "turist",
        "ugnsbur", "ungdom", "union", "utkast", "utpost",
        "vandal", "vandring", "vanster", "vardag", "varsel", "vasall",
        "vimpel", "vindel", "vision", "vokalen", "vulkan",
        "zeppelinare", "zenit",

        // Fler adjektiv och adverb
        "aktiv", "atal", "besk", "bitter", "blank", "blind", "blodig",
        "brant", "briljant", "brokig", "brutal", "dalig", "direkt",
        "diskret", "driven", "duktig", "dunkel", "dyrbar", "effektiv",
        "eget", "enad", "ensam", "exakt", "extra", "falsk", "farlig",
        "fast", "fatal", "fertil", "finurlig", "flyktig", "fokuserad",
        "formell", "framt", "frodig", "fruktbar", "fyndig", "galen",
        "genial", "global", "gnidig", "godmodig", "gyllene", "halig",
        "hastig", "helig", "hemlig", "heroisk", "himlask", "himmelsk",
        "humant", "ideal", "intern", "jovial", "julig", "kapabel",
        "klassisk", "konkret", "kreativ", "kritisk", "kronisk", "kubisk",
        "kulig", "lantlig", "lateral", "lekfull", "levande", "livlig",
        "ljummen", "ljudlig", "lokal", "lojal", "lovlig", "lugnt",
        "lycklig", "makaber", "mager", "manlig", "massiv", "medveten",
        "mental", "modern", "modest", "mojlig", "morsk", "mottaglig",
        "munter", "murbiten", "mystisk", "nasal", "negativ", "neutral",
        "nobel", "normal", "nykter", "nyttig", "obskyr", "ombedd",
        "opolerad", "optimal", "ordrik", "original", "passiv", "perfekt",
        "platt", "positiv", "praktisk", "prima", "privat", "profan",
        "proper", "publik", "rakryggad", "rappt", "rejal", "robust",
        "romantisk", "rymlig", "saktlig", "selektiv", "senior",
        "simpel", "sinrik", "sjyst", "skeptisk", "slarvig", "slipprig",
        "snyggt", "sobert", "social", "solid", "speciell", "spontan",
        "statisk", "stram", "strikt", "subtil", "svag", "syrlig",
        "taktisk", "talrik", "tapper", "torftig", "total", "tragisk",
        "trivial", "tropisk", "trotsig", "typisk", "udda", "unik",
        "urban", "urblekt", "vanligt", "vemodig", "verbal", "verklig",
        "viktig", "vuxen", "ytlig",

        // Fler verb
        "addera", "avsluta", "befordra", "bereda", "beskriva", "bestiga",
        "beundra", "bjuda", "bruka", "dagga", "dikta", "dreja",
        "dryfta", "duka", "elda", "erkanna", "erbjuda", "fajna",
        "flacka", "flyga", "forska", "fresta", "fundera", "galoppera",
        "glimma", "gnugga", "granska", "gripa", "gro", "hamra",
        "harkla", "hasta", "hissa", "hosta", "hugsa", "imponera",
        "jaga", "jubla", "kackla", "karva", "klatta", "klia", "klippa",
        "knastra", "knega", "knoga", "kopiera", "korta", "krama",
        "kvava", "kyla", "lagra", "locka", "lodda", "lyfta", "mangla",
        "maska", "mocka", "morka", "nagga", "nita", "nosa", "nysta",
        "narra", "odla", "ordna", "plana", "prata", "pressa",
        "ratta", "runna", "rycka", "salta", "segla", "skotta",
        "slira", "smyga", "snurra", "spela", "spotta", "sprida",
        "stampa", "steka", "sticka", "stuva", "sveda", "tapetsera",
        "torka", "trampa", "trava", "troda", "tugga", "tvinga",
        "vakta", "verka", "vicka", "vrida",

        // Geografi och platser
        "bredd", "bukt", "delta", "falt", "faste", "halvon", "holme",
        "kanal", "kulle", "miljon", "norra", "platsen", "region",
        "riktning", "sjostrand", "soder", "terrang", "trakt", "udde",
        "uppland", "vastra", "viken", "ostra",

        // Väder och klimat
        "blixten", "bris", "byar", "dagg", "dis", "dager", "fuktig",
        "grader", "gryning", "hagel", "himmel", "hetta", "iskall",
        "kyla", "kvav", "ljummen", "mildvader", "mulet", "orkan",
        "regn", "rimfrost", "skymning", "snoflingor", "solsken",
        "storm", "stralande", "dimma", "tjocka", "torka", "vindby",
        "varmebolja", "aska",

        // Sjöfart och resor
        "ankar", "akter", "bogser", "brygga", "farled", "fiskehamn",
        "flotte", "fyren", "jollar", "kapten", "kompass", "lots",
        "masten", "roddbat", "seglet", "skeppet", "slupen", "staven",
        "styrbord", "trossar",

        // Sport och spel
        "bollen", "galopp", "gransen", "hockey", "hopp", "kast",
        "lagets", "lopp", "match", "medal", "pokal", "racket",
        "rekord", "runda", "serv", "simning", "slalom", "spark",
        "sprint", "styrka", "tavling", "vinst",

        // Hantverkord
        "ambolt", "borste", "dragg", "gjuta", "hampa", "kisel",
        "koppla", "latta", "nagel", "press", "revel", "slipa",
        "spolar", "svarva", "tappar", "trissa", "vikta",

        // Textil och kläder
        "brokad", "draperi", "fibrer", "foder", "garner", "gobelangs",
        "jacka", "kjol", "krage", "mantel", "mockajacka", "overall",
        "sammet", "satin", "skinn", "strumpa", "sybehorsaffar", "tygbit",
        "ullgarn", "vante", "vavnad", "ylleplagg",

        // Matematik och vetenskap
        "atom", "belopp", "cirkel", "data", "ekvation", "faktor",
        "formel", "grad", "halva", "index", "kurva", "linje",
        "massa", "neutron", "omega", "parabel", "procent", "proton",
        "radie", "summa", "tyngd", "vektor", "vinkel", "volym",

        // Musik (ytterligare)
        "allegro", "balalaika", "cello", "dikt", "fanfar", "gitarr",
        "konsert", "mandolin", "munspel", "noter", "refrang", "stradivarius",
        "symfoni", "tamburin", "ukulele", "vibrato",

        // Historiska och kulturella
        "adel", "baron", "borgar", "drottning", "furste", "gille",
        "herald", "huskarl", "jarl", "kloster", "korsriddare",
        "landsknekt", "legat", "moras", "paladin", "riksdag",
        "skeppslag", "stenmurar", "tingshus", "vikingar",

        // Ytterligare substantiv
        "almanacka", "ambition", "arsenal", "avsikt", "ballong",
        "befallning", "beskydd", "bevarande", "bonaden", "borjan",
        "dammig", "diamant", "diskurs", "drivkraft", "eftertanke",
        "embargo", "epoken", "erfarenhet", "explosion", "fakir",
        "fanbarer", "fantasi", "fasett", "favorit", "fenomen",
        "fiktion", "fiskare", "fjader", "folkmusik", "fontaner",
        "froknars", "fullmane", "fyrbak",
        "garderob", "gasell", "gavlan", "geografi", "gestalt",
        "glasyr", "glitter", "granat", "gravsten", "grottfolk",
        "grundval", "guldsmeden", "gungbrada",
        "halvmane", "hamster", "harpun", "hemvist", "horisont",
        "husbonde", "hymnal",
        "illusion", "infart", "initial", "insegel",
        "kapitel", "karolin", "kaskad", "klippan", "knallert",
        "kobolt", "koloss", "kondor", "kontakt", "krater",
        "kubben", "kunglig", "kupolen", "kvarnen",
        "labyrint", "lagunen", "lanterna", "leksak", "likvid",
        "lustgard", "lojrom",
        "manifest", "marknad", "medalj", "mikrofon", "mineral",
        "mittfalt", "monark", "mullbad", "murverk",
        "nattprat", "nomad", "nordvast", "notarie",
        "omdome", "orkester", "ormbunke",
        "palats", "paragon", "patriark", "pergament", "piaster",
        "platina", "plundra", "polarvind", "posturera", "prydnad",
        "radhus", "rankning", "reaktion", "regnmoln", "replik",
        "ridning", "rondell", "rutiner",
        "sabbat", "safiren", "sandkorn", "sentens", "silhuett",
        "sjukdom", "skadedjur", "skeppsbrott", "skorstenspipa",
        "smycke", "snorkla", "soldis", "spalten", "speleman",
        "stadsport", "stenhus", "stiernor", "stormakt", "studsare",
        "sultan", "svordomar",
        "talesman", "termin", "tiggarens", "timmerman", "torsdag",
        "trafikljus", "trakten", "trumpeten", "tunnan",
        "underton", "uppfinning", "ursinnig",
        "valnoten", "vandalism", "vargskinn", "vassbotten",
        "vigselring", "vindruvor", "volymen", "vackerklocka",

        // Ytterligare ord för att nå 2048
        "abborre", "akacia", "akvarium", "altan", "angest",
        "antilop", "apelsin", "aprikos", "avgrund", "avlopp",
        "bakelse", "balja", "bambu", "barndom", "basalt",
        "bedraga", "behaga", "bergstopp", "besatt", "bestig",
        "betsel", "bigarr", "bikupa", "bindel", "biskop",
        "bister", "blandning", "blodsten", "blott", "bockhorn",
        "bollspel", "bomull", "boskap", "brakseger", "bremsa",
        "brinken", "broder", "brottning", "brunsten", "bussig",
        "dammsugar", "daning", "dekis", "delfin", "demonisk",
        "despot", "diplomat", "djurpark", "docent", "domkyrka",
        "donator", "dossier", "drakar", "drivhus", "dubbelt",
        "durken", "duvslag",
        "efemera", "eldfast", "element", "emigrant", "eminent",
        "engagemang", "entusiastisk", "eskortera",
        "fackla", "faktiskt", "fallskarm", "famntak", "farkost",
        "fartfylld", "fasoner", "fattigdom", "felslut", "fenrik",
        "festival", "fiende", "filbunke", "filosofi", "finsmed",
        "fjaller", "fjollig", "fladdermus", "flamman", "flygplan",
        "folkmassa", "folkton", "fordon", "forpost", "forsommaren",
        "forvaning", "fristad", "frostbiten", "frukosten", "fuglen",
        "gadda", "galoscher", "garnison", "gatukonst", "gavmild",
        "genombrott", "gestalt", "gideon", "gimbal", "gjuteri",
        "glasklar", "glesa", "glimten", "golvur", "gorilla",
        "grankotte", "granskog", "gravsten", "grislyng", "grottan",
        "grottmalning", "gruvort", "grundlig", "gruvfogde", "gynnare",
        "halvdag", "hamnkran", "hanarsson", "harkling", "harpist",
        "hasselbusk", "havtorn", "hejdlost", "herrgard", "hjalmriddare",
        "hjulspinne", "hoppfull", "hornblast", "hummerbo", "hundkoja",
        "hurtbulle", "hvirvel", "hyresvaerd",
        "intyg", "isbjorn", "isbana",
        "jakthorn", "jordnot", "julgran",
        "kadaver", "kaktusar", "kaninbo", "kapsyl", "karosseri",
        "kaskelot", "kaskad", "kastanj", "katapult", "kemikalier",
        "klockrent", "klosett", "knoppig", "knorr", "kolmila",
        "konditor", "korsfararens", "kostym", "kragsten", "kransband",
        "kriminell", "kristallklar", "krokus", "krumelur", "kryddnejlika",
        "kryptisk", "kullersten", "kungsorn", "kvastlik", "kvicksilver",
        "lagbok", "lagkamrat", "lagom", "landsort", "lantsort",
        "lekplats", "lektion", "lingonsylt", "livbat", "ljuskrona",
        "lockfagel", "lokomotiv", "lungmossa", "lustresa", "luthmaker",
        "madrass", "mangold", "marginal", "markbuske", "matbord",
        "matjord", "medborgare", "mervaerde", "midsommar", "minaret",
        "mistel", "mjolbagge", "molnbank", "monsun", "mortel",
        "murslev", "mustang", "myrsloek",
    ]
}
